# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_fillablepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillablepdf',
            name='name',
            field=models.CharField(default='Sample pdf', max_length=50),
            preserve_default=False,
        ),
    ]
