# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intake.anonymous_names


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0003_fillablepdf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.IntegerField(choices=[(4, 'Opened'), (5, 'Procesed'), (1, 'QA Reviewed'), (2, 'Confirmation Sent'), (3, 'Submitted'), (6, 'Follow-up sent'), (7, 'Follow-up answer received'), (8, 'Deemed eligible'), (9, 'Deemed ineligible')])),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='anonymous_name',
            field=models.CharField(default=intake.anonymous_names.generate, max_length=60),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='due_for_followup',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='followup_answered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='followup_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='old_uuid',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='opened_by_agency',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='processed_by_agency',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='reviewed_by_staff',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='submitted_to_agency',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='told_eligible',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='told_ineligible',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.FormSubmission'),
        ),
        migrations.AddField(
            model_name='applicationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
