# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0004_auto_20160603_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'read'), (3, 'updated'), (4, 'deleted')])),
                ('updated_field', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationlog',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='applicationlog',
            name='user',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='confirmation_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='ApplicationLog',
        ),
        migrations.AddField(
            model_name='applicationlogentry',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.FormSubmission'),
        ),
        migrations.AddField(
            model_name='applicationlogentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
