# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import intake.models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_auto_20160614_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlogentry',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='applicationlogentry',
            name='updated_field',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='confirmation_sent',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='due_for_followup',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='followup_answered',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='followup_sent',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='opened_by_agency',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='processed_by_agency',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='reviewed_by_staff',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='submitted_to_agency',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='told_eligible',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='told_ineligible',
        ),
        migrations.AddField(
            model_name='applicationlogentry',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'opened'), (2, 'referred'), (3, 'processed'), (4, 'deleted')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='old_uuid',
            field=models.CharField(default=intake.models.gen_uuid, max_length=34, unique=True),
        ),
    ]
