# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0010_auto_20160706_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationsentlogentry',
            name='message_sent',
            field=models.TextField(blank=True),
        ),
    ]
