# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0011_confirmationsentlogentry_message_sent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmationSentLogEntry',
            new_name='ApplicantContactedLogEntry',
        ),
    ]
