# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0012_auto_20160706_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='counties',
            field=models.ManyToManyField(related_name='submissions', to='intake.County'),
        ),
    ]
