# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0013_add_county_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='name',
            field=models.TextField(default='San Francisco'),
            preserve_default=False,
        ),
    ]
