# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:26
from __future__ import unicode_literals
from django.db import migrations

from project.migration_utils import FixtureDataMigration


class AddDefaultCounties(FixtureDataMigration):
    fixture_files = [
        ('intake', '0015_add_default_counties_data.json')
    ]

    model_classes = [
        ('intake', 'County')
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0014_county_name'),
        ('user_accounts', '0006_add_county_model'),
    ]

    operations = [
        migrations.RunPython(
            AddDefaultCounties.forward,
            AddDefaultCounties.reverse)
    ]
