# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_add_profiles_related_name_to_organization'),
        ('intake', '0015_add_default_counties'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlogentry',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='user_accounts.Organization'),
        ),
    ]
