# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_add_profiles_related_name_to_organization'),
        ('intake', '0016_applicationlogentry_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillablepdf',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='user_accounts.Organization'),
        ),
    ]
