# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 19:43
from __future__ import unicode_literals

from django.db import migrations

answer_keys = [
    'prefers_email',
    'prefers_sms',
    'prefers_snailmail',
    'prefers_voicemail',
]

def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    FormSubmission = apps.get_model('intake', 'FormSubmission')
    submissions = FormSubmission.objects.using(db_alias).all()
    for submission in submissions:
        preferences = []
        for key in answer_keys:
            if key in submission.answers:
                submission.answers.pop(key)
                preferences.append(key)
        submission.answers['contact_preferences'] = preferences
        submission.save()


def backward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    FormSubmission = apps.get_model('intake', 'FormSubmission')
    submissions = FormSubmission.objects.using(db_alias).all()
    for submission in submissions:
        preferences = submission.answers.pop('contact_preferences', [])
        for key in answer_keys:
            if key in preferences:
                submission.answers[key] = 'yes'
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0018_add_default_org_to_pdfs_and_logs'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
