# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_add_slugs_to_orgs'),
        ('intake', '0019_update_contact_preferences_answer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='organizations',
            field=models.ManyToManyField(related_name='submissions', to='user_accounts.Organization'),
        ),
    ]
