# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 17:10
from __future__ import unicode_literals

from django.db import migrations
from intake.constants import Organizations, Counties


def get_classes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    FormSubmission = apps.get_model(
        'intake', 'FormSubmission').objects.using(db_alias)
    Organization = apps.get_model(
        'user_accounts', 'Organization').objects.using(db_alias)
    return Organization, FormSubmission


def forward(*args):
    Organization, FormSubmission = get_classes(*args)
    for sub in FormSubmission.all():
        counties = sub.counties.all()
        for county in counties:
            for org in Organization.all():
                if org.county == county:
                    sub.organizations.add(org)

def backward(*args):
    Organization, FormSubmission = get_classes(*args)
    for sub in FormSubmission.all():
        sub.organizations.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0020_formsubmission_organizations'),
        ('user_accounts', '0009_add_slugs_to_orgs'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
