# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_organization_confirmation_message_contact_info_etc'),
        ('intake', '0021_tie_orgs_to_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('original_pdf', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='intake.FillablePDF')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.FormSubmission')),
            ],
        ),
    ]
