# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_organization_confirmation_message_contact_info_etc'),
        ('intake', '0022_filledpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundled_pdf', models.FileField(upload_to='pdf_bundles/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='user_accounts.Organization')),
                ('submissions', models.ManyToManyField(related_name='bundles', to='intake.FormSubmission')),
            ],
        ),
    ]
