# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0022_filledpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filledpdf',
            name='organization',
        ),
    ]
