# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0023_applicationbundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationbundle',
            name='bundled_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_bundles/'),
        ),
    ]
