# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0023_remove_filledpdf_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filledpdf',
            old_name='orginal_pdf',
            new_name='original_pdf',
        ),
    ]
