# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0024_app_bundle_pdf_not_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='counties',
        ),
    ]
