# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0028_formsubmission_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationevent',
            options={'ordering': ['-time']},
        ),
    ]
