# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import intake.models.form_submission


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0029_applicationevent_order_by_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('source', models.TextField(null=True)),
                ('referrer', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='anonymous_name',
            field=models.CharField(default=intake.models.form_submission.generate_pseudonym, max_length=60),
        ),
        migrations.AddField(
            model_name='applicant',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Visitor'),
        ),
    ]
