# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0030_add_visitor_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'permissions': (('view_app_stats', 'Can see detailed aggregate information about apps'),)},
        ),
    ]
