# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0031_add_view_app_stats_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'permissions': (('view_app_stats', 'Can see detailed aggregate information about apps'), ('view_app_details', 'Can see detail information about individual apps'))},
        ),
    ]
