# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0032_add_view_app_details_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ip_address',
            field=models.TextField(null=True),
        ),
    ]
