# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0033_visitor_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateSubmissionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='duplicate_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='intake.DuplicateSubmissionSet'),
        ),
    ]
