# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0035_applicationnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationnote',
            options={'ordering': ['-created'], 'permissions': (('intake.view_application_note', 'Can read the contents of notes from followups'),)},
        ),
    ]
