# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-03 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0036_add_view_app_notes_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='intake.FormSubmission')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_submissiontaglink_items', to='taggit.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='intake.SubmissionTagLink', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
