# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('intake', '0036_add_view_app_notes_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.FormSubmission')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_applicationtag_items', to='taggit.Tag')),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'permissions': (('intake.view_app_stats', 'Can see detailed aggregate information about apps'), ('intake.view_app_details', 'Can see detail information about individual apps'))},
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='intake.ApplicationTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
