# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0037_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('display_name', models.TextField()),
                ('template', models.TextField()),
                ('help_text', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('display_name', models.TextField()),
                ('template', models.TextField()),
                ('help_text', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        )
    ]
