# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0039_create_status_update_without_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('base_message', models.TextField()),
                ('sent_message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intake.StatusUpdate')),
            ],
        )
    ]
