# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0040_create_status_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextstep',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
