# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0042_fix_permissions_and_non_db_model_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdate',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='intake.Application'),
        ),
    ]
