# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0044_one_to_one_mapping_between_status_update_and_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statustype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
