# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import intake.validators


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0047_graduate_fields_from_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextstep',
            name='template',
            field=models.TextField(blank=True, validators=[intake.validators.TemplateFieldValidator()]),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='template',
            field=models.TextField(blank=True, validators=[intake.validators.TemplateFieldValidator()]),
        ),
    ]
