# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0048_template_field_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, null=True),
        ),
    ]
