# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0048_template_field_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstep',
            name='is_a_status_update_choice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statustype',
            name='is_a_status_update_choice',
            field=models.BooleanField(default=True),
        ),
    ]
