# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0049_template_option_is_a_status_update_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(null=True),
        )
    ]
