# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:54
from __future__ import unicode_literals

from django.db import migrations
import uuid


def set_uuids(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Application = apps.get_model('intake', 'Application')
    Applicant = apps.get_model('intake', 'Applicant')
    Visitor = apps.get_model('intake', 'Visitor')
    apps = Application.objects.using(db_alias).all()
    applicants = Applicant.objects.using(db_alias).all()
    visitors = Visitor.objects.using(db_alias).all()
    gen_uuids(apps)
    gen_uuids(applicants)
    gen_uuids(visitors)


def gen_uuids(items):
    for item in items:
        item.uuid = uuid.uuid4()
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0049_add_uuid_fields'),
    ]

    '''
    Following recommendations in Django documentation re: ensuring unique UUIDs
    during migrations -- this involves splitting into 3 migration files, so if
    we want to revert, #0049 - #0051 are relevant here.

    In migration 2 of 3, we generate unique values for the UUID fields
    '''

    operations = [
        migrations.RunPython(set_uuids, reverse_code=migrations.RunPython.noop),
    ]
