# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:08
from __future__ import unicode_literals
from django.db import migrations


def correct_default_dates_on_applications(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Application = apps.get_model('intake', 'Application')
    apps = Application.objects.using(db_alias).all()
    for app in apps:
        if not app.created:
            app.created = app.form_submission.date_received
            app.updated = app.created
            app.save()


def dont_erase_dates_on_applications(apps, schema_editor):
    # Dont erase the dates. Literally do nothing.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0050_application_created_updated'),
    ]

    operations = [
        migrations.RunPython(
            correct_default_dates_on_applications,
            dont_erase_dates_on_applications),
    ]
