# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0053_populate_uuid_values'),
    ]

    '''
    Following recommendations in Django documentation re: ensuring unique UUIDs
    during migrations -- this involves splitting into 3 migration files, so if
    we want to revert, #0049 - #0051 are relevant here.

    In migration 3 of 3, we remove the null state from the UUID field
    definitions and set to unique
    '''

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
