# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0054_graduate_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
