# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 23:07
from __future__ import unicode_literals

from django.db import migrations


def add_visitors_for_applicants(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Applicant = apps.get_model('intake', 'Applicant')
    Visitor = apps.get_model('intake', 'Visitor')
    ApplicationEvent = apps.get_model('intake', 'ApplicationEvent')
    applicants = Applicant.objects.using(db_alias).all()
    for app in applicants:
        if not app.visitor_id:
            visitor = Visitor()
            visitor.save()
            app.visitor_id = visitor.id
            app.save()
            first_app_event = ApplicationEvent.objects.filter(
                applicant_id=app.id).order_by('time').first()
            visitor.first_visit = first_app_event.time
            visitor.save()


def dont_erase_visitors(apps, schema_editor):
    # Dont erase the visitors. Literally do nothing.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0055_visitor_uuid'),
    ]

    operations = [
            migrations.RunPython(
                add_visitors_for_applicants,
                dont_erase_visitors),
    ]
