# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0056_backfill_visitors_for_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intake.Visitor'),
        ),
    ]
