# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 18:26
from __future__ import unicode_literals

from django.db import migrations, models
from intake.models import ApplicationEvent


def backfill_submissions_with_followups_from_events(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    FormSubmission = apps.get_model('intake', 'FormSubmission')
    subs = FormSubmission.objects.using(db_alias).all()
    subs.filter(
            applicant__events__name=ApplicationEvent.FOLLOWUP_SENT
        ).distinct().update(has_been_sent_followup=True)


def reset_new_flag_field_on_sub(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    FormSubmission = apps.get_model('intake', 'FormSubmission')
    subs = FormSubmission.objects.using(db_alias).all()
    subs.update(has_been_sent_followup=False)


def backfill_applications_with_has_been_opened(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Application = apps.get_model('intake', 'Application')
    ApplicationLogEntry = apps.get_model('intake', 'ApplicationLogEntry')
    apps = Application.objects.using(db_alias).all()
    for app in apps:
        app.has_been_opened = ApplicationLogEntry.objects.filter(
            organization=app.organization, submission=app.form_submission,
            event_type=1).exists()
        app.save()


def reset_new_flag_field_on_app(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Application = apps.get_model('intake', 'Application')
    apps = Application.objects.using(db_alias).all()
    apps.update(has_been_opened=False)


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0057_applicant_visitor_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_been_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
                backfill_applications_with_has_been_opened,
                reset_new_flag_field_on_app),
        migrations.AddField(
            model_name='formsubmission',
            name='has_been_sent_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
                backfill_submissions_with_followups_from_events,
                reset_new_flag_field_on_sub),
    ]
