# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0059_newappspdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newappspdf',
            name='pdf',
            field=models.FileField(upload_to='prebuilt_newapps_pdfs/'),
        ),
    ]
