# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0059_prebuiltpdfbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='user_agent',
            field=models.TextField(default=''),
        ),
    ]
