# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0060_visitor_locale_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
