# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0062_add_id_purgedformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'purged"."intake_application',
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_application AS
            SELECT %s From intake_application;
            """ %
            ', '.join([
                'id',
                'organization_id',
                'formsubmission_id',
                'was_transferred_out',
                'has_been_opened',
            ]),
            """DROP VIEW purged.intake_application;
            """),
        migrations.CreateModel(
            name='PurgedStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'purged"."intake_statusupdate',
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_statusupdate AS
            SELECT %s From intake_statusupdate;
            """ %
            ', '.join([
                'id',
                'created',
                'updated',
                'status_type_id',
                'author_id',
                'application_id',
            ]),
            """DROP VIEW purged.intake_statusupdate;
            """),
    ]
