# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0063_purgedapplication_purgedstatusupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_visitor',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_visitor AS
            SELECT %s From intake_visitor;
            """ %
            ', '.join([
                'id',
                'uuid',
                'first_visit',
                'source',
                'referrer',
                'locale',
            ]),
            """DROP VIEW purged.intake_visitor;
            """),
    ]
