# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0064_purgedvisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_applicant',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_applicant AS
            SELECT %s From intake_applicant;
            """ %
            ', '.join([
                'id',
                'visitor_id',
            ]),
            """DROP VIEW purged.intake_applicant;
            """),
    ]
