# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0065_purgedapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedApplicationNote',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_applicationnote',
                'managed': False,
            },
        ),

        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_applicationnote AS
            SELECT %s From intake_applicationnote;
            """ %
            ', '.join([
                'id',
                'created',
                'user_id',
                'submission_id',
            ]),
            """DROP VIEW purged.intake_applicationnote;
            """),
    ]
