# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0066_purgedapplicationnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_county',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_county AS
            SELECT %s FROM intake_county;
            """ %
            ', '.join([
                'id',
                'slug',
                'name',
                'description',
            ]),
            """DROP VIEW purged.intake_county;
            """),
        migrations.CreateModel(
            name='PurgedNextStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_nextstep',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_nextstep AS
            SELECT %s FROM intake_nextstep;
            """ %
            ', '.join([
                'id',
                'label',
                'display_name',
                'template',
                'help_text',
                'slug',
                'is_active',
                'is_a_status_update_choice',
            ]),
            """DROP VIEW purged.intake_nextstep;
            """),
        migrations.CreateModel(
            name='PurgedStatusNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_statusnotification',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_statusnotification AS
            SELECT %s FROM intake_statusnotification;
            """ %
            ', '.join([
                'id',
                'status_update_id',
                'created',
            ]),
            """DROP VIEW purged.intake_statusnotification;
            """),
        migrations.CreateModel(
            name='PurgedStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_statustype',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_statustype AS
            SELECT %s FROM intake_statustype;
            """ %
            ', '.join([
                'id',
                'label',
                'display_name',
                'template',
                'help_text',
                'slug',
                'is_active',
                'is_a_status_update_choice',
            ]),
            """DROP VIEW purged.intake_statustype;
            """),
        migrations.CreateModel(
            name='PurgedSubmissionTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."intake_submissiontaglink',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_submissiontaglink AS
            SELECT * FROM intake_submissiontaglink;
            """,
            """DROP VIEW purged.intake_submissiontaglink;
            """),
        migrations.CreateModel(
            name='PurgedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purged"."taggit_tag',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.taggit_tag AS
            SELECT * FROM taggit_tag;
            """,
            """DROP VIEW purged.taggit_tag;
            """),
    ]
