# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake',
         '0068_purgedformsubmission_add_applicant_id'),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.intake_application AS
            SELECT %s From intake_application;
            """ %
            ', '.join([
                'id',
                'organization_id',
                'formsubmission_id',
                'was_transferred_out',
                'has_been_opened',
                'created',
                'updated',
            ]),
            """DROP VIEW purged.intake_application;
            """
        ),
    ]
