# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0070_formsubmission_unlisted_counties'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstep',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statustype',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
