# Generated by Django 2.0.13 on 2020-01-15 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0071_add_display_order_to_template_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='intake.Visitor'),
        ),
        migrations.AlterField(
            model_name='applicationnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='duplicate_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='intake.DuplicateSubmissionSet'),
        ),
    ]
