# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='title',
            field=models.CharField(default='Placeholder', max_length=64),
            preserve_default=False,
        ),
    ]
