# Generated by Django 2.2.13 on 2020-06-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
