# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 19:22
from __future__ import unicode_literals

from django.db import migrations

from project.migration_utils import FixtureDataMigration


class AddDefaultOrgsAndLinkToCounties(FixtureDataMigration):
    """Loads org data from a fixture

    `forward` loads the fixture
    `reverse` will unlink counties from orgs
    """
    fixture_files = [
        ('user_accounts', '0007_add_default_orgs_for_counties_data.json')
    ]
    model_classes = [
        ('user_accounts', 'Organization')
    ]

    @classmethod
    def reverse(cls, *args):
        """just unsets the 'county' attribute on each org
        Any added orgs remain in the database
        """
        Organization = list(cls.get_classes(*args))[0]
        for instance in Organization.all():
            instance.county = None
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_add_county_model'),
        ('intake', '0015_add_default_counties'),
    ]

    operations = [
            migrations.RunPython(
                AddDefaultOrgsAndLinkToCounties.forward,
                AddDefaultOrgsAndLinkToCounties.reverse)
    ]
