# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_add_slugs_to_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='new_submission_confirmation_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='requires_declaration_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='requires_rap_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
