# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_organization_confirmation_message_contact_info_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_pdf_only',
            field=models.BooleanField(default=False),
        ),
    ]
