# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0013_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='new_submission_confirmation_message',
            new_name='long_confirmation_message',
        ),
        migrations.AddField(
            model_name='organization',
            name='short_confirmation_message',
            field=models.TextField(blank=True),
        ),
    ]
