# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('user_accounts', '0015_organization_notify_on_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='groups',
            field=models.ManyToManyField(related_name='invitations', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='should_get_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
