# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0016_add_more_invitation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='long_followup_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_followup_message',
            field=models.TextField(blank=True),
        ),
    ]
