# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0017_organization_followup_message_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_accepting_applications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_checking_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
