# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0018_org_accepting_apps_checking_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
    ]
