# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0019_order_orgs_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
