# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0020_organization_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='can_transfer_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='transfer_partners',
            field=models.ManyToManyField(blank=True, related_name='_organization_transfer_partners_+', to='user_accounts.Organization'),
        ),
    ]
