# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0021_organization_transfer_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='needs_applicant_followups',
            field=models.BooleanField(default=False),
        ),
    ]
