# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0022_organization_needs_applicant_followups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fax_number',
            field=models.TextField(blank=True),
        ),
    ]
