# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0060_auto_20170707_1930'),
        ('user_accounts', '0024_userprofile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visitors',
            field=models.ManyToManyField(related_name='users', to='intake.Visitor'),
        ),
    ]
