# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0061_purgedformsubmission'),
        ('user_accounts', '0024_userprofile_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgedOrganization',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'purged"."user_accounts_organization',
            },
        ),
        migrations.RunSQL(
            """CREATE OR REPLACE VIEW purged.user_accounts_organization AS
            SELECT * From user_accounts_organization;
            """,
            """DROP VIEW purged.user_accounts_organization;
            """),
    ]
