# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 21:18
from __future__ import unicode_literals

from django.db import migrations


def delete_hayward_clean_slate_clinic(apps, schema_editor):
    Address = apps.get_model('user_accounts', 'Address')
    Address.objects.filter(name='Hayward Clean Slate Walk-in Clinic').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0025_purgedorganization'),
    ]

    operations = [
        migrations.RunPython(delete_hayward_clean_slate_clinic)
    ]
