# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialPartnerLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('organization_name', models.TextField()),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
